name: config_full
description: '迁移自旧 json，途经: 洛阳 → 嵩山 → 幽州 → 姑苏 → 杭州 → 泉州 → 龙泉镇 → 双王镇 → 南阳渡 → 太乙山 → 凤鸣集 → 成都'
loop_count: 1
loop_interval: 0
starting_map: 洛阳
steps:
- type: move
  at_map: 洛阳
  path:
  - [10, 18]
  - [14, 22]
  - [17, 21]
- type: buy
  items:
  - [4, 1]
  - [5, 1]
  - [6, 1]
- type: move
  at_map: 洛阳
  path:
  - [17, 21]
  - [18, 26]
  - [20, 30]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  delay: 4.5
- type: move
  at_map: 洛阳
  path:
  - [20, 30]
  - [17, 28]
- type: buy
  items:
  - [1, 5]
- type: move
  at_map: 洛阳
  path:
  - [17, 28]
  - [24, 29]
- type: buy
  items:
  - [1, 5]
  - [2, 5]
  - [3, 5]
  - [4, 5]
  - [5, 3]
  - [6, 3]
  - [7, 3]
  - [8, 3]
- type: move
  at_map: 洛阳
  path:
  - [24, 29]
  - [24, 30]
- type: buy
  items:
  - [1, 5]
  - [3, 5]
- type: travel
  to: 嵩山
- type: move
  at_map: 嵩山
  path:
  - [19, 32]
  - [10, 32]
  - [10, 15]
  - [13, 14]
- type: buy
  items:
  - [1, 1]
- type: travel
  to: 幽州
- type: move
  at_map: 幽州
  path:
  - [11, 22]
  - [16, 21]
- type: buy
  items:
  - [4, 1]
  - [7, 2]
- type: move
  at_map: 幽州
  path:
  - [16, 21]
  - [16, 28]
- type: buy
  items:
  - [5, 2]
- type: move
  at_map: 幽州
  path:
  - [16, 28]
  - [21, 28]
  - [25, 32]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  delay: 4.5
- type: travel
  to: 姑苏
- type: move
  at_map: 姑苏
  path:
  - [17, 11]
  - [19, 17]
  - [20, 20]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  delay: 4.5
- type: move
  at_map: 姑苏
  path:
  - [20, 20]
  - [15, 17]
  - [15, 16]
- type: buy
  items:
  - [8, 1]
- type: move
  at_map: 姑苏
  path:
  - [15, 16]
  - [10, 17]
  - [7, 17]
- type: button
  name: table_1
  skip: 1
- type: button
  name: chat_2
  delay: 4.5
- type: travel
  to: 杭州
- type: move
  at_map: 杭州
  path:
  - [31, 13]
  - [32, 6]
  - [31, 3]
- type: button
  name: table_1
  skip: 1
- type: button
  name: chat_2
  delay: 4.5
- type: move
  at_map: 杭州
  path:
  - [31, 3]
  - [32, 10]
  - [32, 15]
  - [25, 15]
  - [25, 25]
  - [15, 25]
  - [10, 22]
  - [10, 18]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  skip: 2
- type: travel
  to: 泉州
- type: move
  at_map: 泉州
  path:
  - [16, 11]
  - [22, 10]
- type: button
  name: table_2
- type: button
  name: chat_2
  delay: 1
- type: buy
  items:
  - [2, 1]
- type: move
  at_map: 泉州
  path:
  - [22, 10]
  - [16, 11]
  - [13, 15]
- type: buy
  items:
  - [7, 1]
  - [8, 1]
- type: travel
  to: 龙泉镇
- type: move
  at_map: 龙泉镇
  path:
  - [12, 7]
  - [18, 6]
  - [23, 4]
  - [23, 1]
- type: button
  name: table_2
- type: button
  name: chat_2
  delay: 1
- type: buy
  items:
  - [3, 5]
- type: move
  at_map: 龙泉镇
  path:
  - [23, 1]
  - [23, 4]
  - [18, 6]
  - [12, 7]
  - [12, 12]
- type: button
  name: table_1
  skip: 1
- type: button
  name: chat_2
  delay: 4.5
- type: move
  at_map: 龙泉镇
  path:
  - [12, 12]
  - [11, 19]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  skip: 1
  delay: 4.5
- type: travel
  to: 双王镇
- type: move
  at_map: 双王镇
  path:
  - [11, 23]
  - [17, 23]
  - [21, 23]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  delay: 4.5
- type: move
  at_map: 双王镇
  path:
  - [21, 23]
  - [22, 27]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  skip: 1
  delay: 4.5
- type: travel
  to: 南阳渡
- type: move
  at_map: 南阳渡
  path:
  - [28, 17]
  - [25, 17]
- type: buy
  items:
  - [1, 3]
- type: move
  at_map: 南阳渡
  path:
  - [25, 17]
  - [24, 20]
- type: buy
  items:
  - [3, 1]
  - [6, 1]
  - [7, 1]
  - [8, 1]
- type: move
  at_map: 南阳渡
  path:
  - [24, 20]
  - [25, 23]
- type: buy
  items:
  - [3, 5]
- type: move
  at_map: 南阳渡
  path:
  - [25, 23]
  - [22, 21]
  - [19, 19]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  delay: 4.5
- type: travel
  to: 太乙山
- type: move
  at_map: 太乙山
  path:
  - [13, 34]
  - [17, 30]
  - [15, 24]
  - [15, 18]
  - [20, 15]
- type: buy
  items:
  - [1, 1]
- type: travel
  to: 凤鸣集
- type: move
  at_map: 凤鸣集
  path:
  - [9, 22]
  - [13, 25]
- type: buy
  items:
  - [3, 1]
  - [6, 1]
  - [8, 1]
- type: move
  at_map: 凤鸣集
  path:
  - [13, 25]
  - [15, 21]
- type: button
  name: table_2
  skip: 1
- type: button
  name: chat_1
  delay: 4.5
- type: travel
  to: 成都
- type: move
  at_map: 成都
  path:
  - [15, 11]
  - [15, 10]
  - [12, 5]
- type: buy
  items:
  - [1, 3]
- type: move
  at_map: 成都
  path:
  - [12, 5]
  - [15, 10]
  - [15, 11]
  - [19, 15]
  - [23, 16]
- type: button
  name: table_3
- type: button
  name: chat_1
  delay: 1
- type: buy
  items:
  - [1, 3]
  - [2, 3]
