name: 十方集
description: '迁移自旧 json，途经: 十方集'
loop_count: 1
loop_interval: 0
starting_map: 十方集
steps:
- type: move
  at_map: 十方集
  path:
  - [5, 23]
  - [5, 22]
- type: button
  name: table_3
  delay: 0.75
- type: move
  at_map: 十方集
  path:
  - [5, 22]
  - [9, 24]
- type: button
  name: table_3
  delay: 0.75
- type: move
  at_map: 十方集
  path:
  - [9, 24]
  - [8, 28]
- type: button
  name: table_3
  delay: 0.75
- type: move
  at_map: 十方集
  path:
  - [8, 28]
  - [4, 26]
- type: button
  name: table_3
  delay: 0.75
- type: move
  at_map: 十方集
  path:
  - [4, 26]
  - [2, 23]
- type: button
  name: table_3
  delay: 0.75
- type: move
  at_map: 十方集
  path:
  - [2, 23]
  - [5, 23]
- type: button
  name: table_3
  delay: 0.75
