roi:
  equipment_name:
    - 0.4201
    - 0.4789
    - 0.5223
    - 0.5221
  refine_count:
    - 0.3997
    - 0.5181
    - 0.5234
    - 0.5698
  base_attrs:
    - 0.604
    - 0.2912
    - 0.7458
    - 0.4247
  extra_attr_1:
    - 0.6037
    - 0.4618
    - 0.7048
    - 0.508
  extra_attr_2:
    - 0.604
    - 0.51
    - 0.7161
    - 0.5587
  extra_attr_3:
    - 0.604
    - 0.5628
    - 0.713
    - 0.6094
  bottom_buttons:
    - 0.3712
    - 0.752
    - 0.8384
    - 0.8635
  material_1:
    - 0.4023
    - 0.7209
    - 0.4757
    - 0.751
  material_2:
    - 0.4975
    - 0.7209
    - 0.5754
    - 0.7495
  cost_money:
    - 0.6621
    - 0.6275
    - 0.7994
    - 0.6792
  balance_money:
    - 0.6588
    - 0.6883
    - 0.8034
    - 0.7405
  new_attr_slot_1:
    - 0.7517
    - 0.4629
    - 0.8508
    - 0.5115
  new_attr_slot_2:
    - 0.752
    - 0.5166
    - 0.852
    - 0.5567
  new_attr_slot_3:
    - 0.7517
    - 0.5633
    - 0.8511
    - 0.6059
button:
  refine:
    - 0.5802
    - 0.7967
  accept:
    - 0.6723
    - 0.7962
  cancel:
    - 0.4853
    - 0.7912
ocr:
  backend: cnocr
  params:
    det_model_name: ch_PP-OCRv4_det
    rec_model_name: scene-densenet_lite_136-gru
    context: cpu
    rec_score_threshold: 0.4
equipment_material_map:
  呼如木甲:
    - 青蝉翼
    - 银两
  乌蚕宝甲:
    - 青蝉翼
    - 银两
  吉达护腰:
    - 青蝉翼
    - 银两
  玉衡护腰:
    - 青蝉翼
    - 银两
  乌斯护腕:
    - 青蝉翼
    - 银两
  紫薇护腕:
    - 青蝉翼
    - 银两
  其木格坠:
    - 昆吾石
    - 银两
  青云坠:
    - 昆吾石
    - 银两
  苏布宝戒:
    - 昆吾石
    - 银两
  青云戒:
    - 昆吾石
    - 银两
  贪狼棍:
    - 昆吾石
    - 银两
  碎虚枪:
    - 昆吾石
    - 银两
  碎月重刀:
    - 昆吾石
    - 银两
  掠影刀:
    - 昆吾石
    - 银两
  万仞重剑:
    - 昆吾石
    - 银两
  巽风剑:
    - 昆吾石
    - 银两
  撼岳掌套:
    - 昆吾石
    - 银两
  破军指套:
    - 昆吾石
    - 银两
  黑杀棍:
    - 昆吾石
    - 银两
  穿云刀:
    - 昆吾石
    - 银两
  止水剑:
    - 昆吾石
    - 银两
  修罗拳套:
    - 昆吾石
    - 银两
delay_after_refine_click: 1.0
delay_after_decision_click: 0.2
poll_interval: 0.2
panel_wait_timeout: 3.0
